// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbgzmudjatphryoohlfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiZ3ptdWRqYXRwaHJ5b29obGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0MzE1OTYsImV4cCI6MjA1NTAwNzU5Nn0.AY-YD-JugqF3_rYhufGIrvKLb735MNjfDcrQG1Js6b4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});