
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ummxlnjjrnwqvuxpkdfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbXhsbmpqcm53cXZ1eHBrZGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MzQ0ODIsImV4cCI6MjA2NzExMDQ4Mn0.sWDaWcgM1POT3zBbc-WY8XU-7xuOTCeQjGzl2LgGO1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
